### ISSUE TITLE
Basic Authentication with CaddyServer is not working for minio store

### ISSUE THREAD

**Issue by Clemens123** [Toumash/mlflow-docker#10]
Hi, love your project, thank you very much for the effort you put in!

I'm trying to add secure authentication to the MLflow-Server and am using Caddy (https://caddyserver.com/) as a reverse proxy.
For MLflow it works fine, but the MinIO-Artifact-Store is just not accessible behind the reverse proxy, I don't know why.
The point is, I need to have access to MLflow Tracking savely online.

Do you have any ideas or suggestions?

Could be a cool addon to the project, too, for people to learn about reverse proxies.

Thanks and best regards!
 Clemens

**Comment by Toumash** [comment]
Did you try using the [official way of using minio + caddy from minio docs](
https://docs.min.io/docs/setup-caddy-proxy-with-minio.html)? 

Whats the problem exactly? Which part does not work (artifacts upload from cli/python or download from mlflow ui?). Could you post some diagram which represents the problematic situation? How did you try to diagnose it?

**Comment by Clemens123** [comment]
Hi Toumash, thanks for answering!

The official way of using minio+caddy that you linked, is outdated, sadly. It is written for Caddyserver v.1.
When I'm using a Caddy-file with the following content:
  ```
my-url.com
  reverse_proxy s3:9000       #"s3" is the MinIO-docker-service
```
opening my-url.com:9000 in the browser redirects me to the MinIO-console-UI at port 9001, but the connection is is marked "not secure" in the address-bar. When I replace 's3:9000 ' with 'mlflow:5000' for the MLflow-tracking, everything works fine and the connection is secure.
I'm wondering whether maybe the connection to port 9000 is actually secure and only the MinIO-redirect to 9001 opens a new, unsafe connection...

**About the idea:** I don't know if you are familiar with Caddyserver, but apart from MinIO it is very easy to get a secure basic authentication up and running! So if you think this would be well-received on youtube, you should go for it :)

**Comment by Toumash** [comment]
Im gonna see whats the problem tomorrow. In the meantime please post your docker-compose with caddyserver setup.
Maybe thats a opportunity to update official minio docs :)

**Comment by Clemens123** [comment]
Caddyfile:
```
my-url.com {
    redir /s3 /s3/
    handle_path /s3/* {
        reverse_proxy s3:9000
    }
    redir /mlflow /mlflow/
    handle_path /mlflow/* {
        reverse_proxy mlflow:5000
    }
    handle {
        reverse_proxy ui:8051        # unrelated service from another docker project
    }
}
```
docker-compose for Caddy:
```
version: "3"
services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /caddy/data:/data
      - /caddy/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
networks:
  default:
    name: proxy-net
```
docker-compose for MLflow (I use the one from this project, just added the "proxy-net"-network to make the services accessible to Caddy):
```
version: '3.2'
services:
  s3:
    restart: always
    image: minio/minio:latest
    container_name: aws-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    command:
      server /date --console-address ":9001"
    networks:
      - default
      - proxy-net
    volumes:
      - ./s3:/date
  db:
      restart: always
      image: mysql/mysql-server:5.7.28
      container_name: mlflow_db
      expose:
          - "3306"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
          - ./dbdata:/var/lib/mysql
      networks:
            - default
  mlflow:
      restart: always
      container_name: tracker_mlflow
      image: tracker_ml
      build:
          context: ./mlflow
          dockerfile: Dockerfile
      ports:
          - "5000:5000"
      environment:
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_DEFAULT_REGION=${AWS_REGION}
          - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      networks:
          - proxy-net
          - default
      entrypoint: ./wait-for-it.sh db:3306 -t 90 -- mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://${AWS_BUCKET_NAME}/ -h 0.0.0.0

networks:
  proxy-net:
      external: true
```
